Closes #46 Zero division bug removed
gb-converter/web-site pull request #48
Opened 2020-12-10 14:28 UTC by monstric93

2020-12-13 16:00 UTC, gb-converter requested changes

2020-12-13 16:00 UTC, gb-converter commented on website/converter_frontend/views.py
>          culc_result = amount_of_currency_from
better to name it calc_result

2020-12-14 18:10 UTC, viktor-filinskij approved these changes

2020-12-14 18:12 UTC, gb-converter approved these changes

2020-12-14 18:13 UTC, merged